const searchActionTypes = {
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  SET_RETURNED_ARTISTS: 'SET_RETURNED_ARTISTS',
  SET_RETURNED_TRACKS: 'SET_RETURNED_TRACKS',
  SET_RETURNED_ALBUMS: 'SET_RETURNED_ALBUMS',
  SET_RETURNED_PLAYLISTS: 'SET_RETURNED_PLAYLISTS'
}

export default searchActionTypes