const searchActionTypes = {
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',

  SET_SEARCH_TERM: 'SET_SEARCH_TERM',

  FETCH_ARTISTS_START: 'FETCH_ARTISTS_START',
  FETCH_ARTISTS_ERROR: 'FETCH_ARTISTS_ERROR',
  FETCH_ARTISTS_SUCCESS: 'FETCH_ARTISTS_SUCCESS',

  SET_RETURNED_TRACKS: 'SET_RETURNED_TRACKS',

  FETCH_ALBUMS_START: 'FETCH_ALBUMS_START',
  FETCH_ALBUMS_ERROR: 'FETCH_ALBUMS_ERROR',
  FETCH_ALBUMS_SUCCESS: 'FETCH_ALBUMS_SUCCESS',

  FETCH_PLAYLISTS_START: 'FETCH_PLAYLISTS_START',
  FETCH_PLAYLISTS_ERROR: 'FETCH_PLAYLISTS_ERROR',
  FETCH_PLAYLISTS_SUCCESS: 'FETCH_PLAYLISTS_SUCCESS'
}

export default searchActionTypes