export const playerActionTypes = {
  SET_RECENT_TRACKS: 'SET_RECENT_TRACKS',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',

  SET_NOW_PLAYING: 'SET_NOW_PLAYING',

  SET_PLAY_QUEUE: 'SET_PLAY_QUEUE',

  FETCH_RECENT_TRACKS_START: 'FETCH_RECENT_TRACKS_START',
  FETCH_RECENT_TRACKS_ERROR: 'FETCH_RECENT_TRACKS_ERROR',
  FETCH_RECENT_TRACKS_SUCCESS: 'FETCH_RECENT_TRACKS_SUCCESS',

  CLEAR_PLAYER: 'CLEAR_PLAYER'
}