export const collectionActionTypes = {
  FETCH_ALBUM_SUCCESS: 'FETCH_ALBUM_SUCCESS',
  REMOVE_ALBUM: 'REMOVE_ALBUM',

  FETCH_PLAYLIST_SUCCESS: 'FETCH_PLAYLIST_SUCCESS',
  REMOVE_PLAYLIST: 'REMOVE_PLAYLIST',

  FETCH_LIKED_TRACKS_SUCCESS: 'FETCH_LIKED_TRACKS_SUCCESS',
  REMOVE_LIKED_TRACKS: 'REMOVE_LIKED_TRACKS',

  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_ERROR: 'FETCH_COLLECTION_ERROR',
}