export const collectionActionTypes = {
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  REMOVE_COLLECTION: 'REMOVE_COLLECTION',
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_ERROR: 'FETCH_COLLECTION_ERROR',

  SET_NEXT: 'SET_NEXT',
  UPDATE_COLLECTION_ITEMS: 'UPDATE_COLLECTION_ITEMS'
}