export const userActionTypes = {
  FETCH_CURRENT_USER_START: 'FETCH_CURRENT_USER_START',
  FETCH_CURRENT_USER_ERROR: 'FETCH_CURRENT_USER_ERROR',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',

  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER',

  FETCH_USER_PLAYLISTS_START: 'FETCH_USER_PLAYLISTS_START',
  FETCH_USER_PLAYLISTS_ERROR: 'FETCH_USER_PLAYLISTS_ERROR',
  FETCH_USER_PLAYLISTS_SUCCESS: 'FETCH_USER_PLAYLISTS_SUCCESS',
}