export const userActionTypes = {
  // SET_CURRENT_USER: 'SET_CURRENT_USER',
  FETCH_CURRENT_USER_START: 'FETCH_CURRENT_USER_START',
  FETCH_CURRENT_USER_ERROR: 'FETCH_CURRENT_USER_ERROR',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER',
  FETCH_USER_PLAYLISTS_START: 'FETCH_USER_PLAYLISTS_START',
  FETCH_USER_PLAYLISTS_ERROR: 'FETCH_USER_PLAYLISTS_ERROR',
  FETCH_USER_PLAYLISTS_SUCCESS: 'FETCH_USER_PLAYLISTS_SUCCESS',
  // SET_USER_PLAYLISTS: 'SET_USER_PLAYLISTS'
}